# version: '3.8'

# services:
#   react-app:
#     build:
#       context: ./frontend
#     ports:
#       - "80:80"

# services:
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     image: doggopawer/healper-frontend:latest  # 이미지 이름 추가
#     volumes:
#       - ./frontend/build:/app/build

#   nginx:
#     image: nginx:alpine
#     depends_on:
#       - frontend
#       # - backend  # backend 서비스도 의존성에 추가
#     volumes:
#       - ./frontend/build:/usr/share/nginx/html
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#       - ./certs:/etc/letsencrypt/live/www.healper.shop  # SSL 인증서 마운트
#     ports:
#       - "80:80"
#       - "443:443"  # HTTPS 포트 추가

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   image: doggopawer/healper-backend:latest  # 이미지 이름 추가
  #   volumes:
  #     - ./backend:/usr/src/app
  #   ports:
  #     - "4000:4000"
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: doggopawer/healper-frontend:latest
    volumes:
      - ./frontend/build:/app/build # 빌드 결과물을 /app/build에 마운트

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # HTTPS 포트 추가
    volumes:
      - ./frontend/build:/usr/share/nginx/html # 빌드 결과물을 Nginx에서 서빙하도록 마운트
      - /etc/letsencrypt/live/www.healper.shop:/etc/letsencrypt/live/www.healper.shop  # SSL 인증서 마운트(변경할 것)
    depends_on:
      - frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: doggopawer/healper-backend:latest # 이미지 이름 추가
    # volumes:
    #   - ./backend:/usr/src/app
    ports:
      - "4000:4000"
