version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: doggopawer/healper-frontend:latest
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048
    volumes:
      - ./frontend/build:/app/build # 호스트의 디렉토리와 컨테이너의 디렉토리를 연결한다.
  nginx:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    image: doggopawer/healper-nginx:latest
    ports:
      - "80:80"
      - "443:443"  # HTTPS 포트 추가
    volumes:
      - ./frontend/build:/usr/share/nginx/html # 빌드 결과물을 Nginx에서 서빙하도록 마운트
      - ./certs:/etc/letsencrypt/live/www.healper.shop
    depends_on:
      - frontend
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: doggopawer/healper-backend:latest # 이미지 이름 추가
    ports:
      - "4000:4000"
